### ISSUE TITLE
Flash fails on redirect using a layout file

### ISSUE THREAD

**Issue by lebogan** [kemalcr/kemal#460]
### Description

Redirect doesn't seem to retain the session flash info. This worked with Crystal 0.24.2 and Kemal 0.21.0.
I am now using Crystal 0.25.0 and Kemal 0.23.0. Reference #375, #444 my rookie mistake which was remedied if this is helpful.

### Steps to Reproduce

1. [First Step]
My route block
```
post "/log" do |env|
  entry = Memo.new
  env.flash["success"] = "Entry successfully added" if save_record(entry, env)
  env.redirect "/logs"
end
```
2. [Second Step]
My layout file
```
    section.container-fluid
      == render "src/views/alerts.slang"
      == content
```
3. [and so on...]
My alerts.slang file
```
- case
- when env.flash["success"]?
    div.alert.alert-success
      == env.flash["success"]?
- when env.flash["info"]?
    div.alert.alert-info
      == env.flash["info"]?
- when env.flash["warning"]?
    div.alert.alert-warning
      == env.flash["warning"]?
- end
```

**Expected behavior:** [What you expect to happen]
When I post I should see an alert box which disappears when I refresh the page.

**Actual behavior:** [What actually happens]
Compile time error: undefined local variable or method 'env

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always fails.

### Versions
Crystal 0.25.0
Kemal 0.23.0
Fedora 27

I have a test app at https://kemal-names.herokuapp.com/ where this works with the older versions, admin/abcdef.

**Comment by lebogan** [comment]
Update:
If I move the flash logic to another file, say `home.slang`, it works. Just doesn't seem to work in the layout file. Hmmmm... Still troubleshooting.

**Comment by lebogan** [comment]
What additional info is needed? I have placed my source at https://github.com/lebogan/netblog.git. My work-around is okay for now. Thanks.
